# Generated by Django 5.0 on 2023-12-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('cargo_volume', models.CharField(max_length=30)),
                ('cargo_value', models.IntegerField(default=0)),
                ('dimensions', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=30)),
                ('number_telephone', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('inn', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('number_telephone', models.CharField(max_length=30)),
                ('salary', models.IntegerField(default=0)),
                ('pasport', models.CharField(max_length=30)),
                ('work_experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_incident', models.CharField(max_length=30)),
                ('date_incident', models.DateField()),
                ('time_incident', models.TimeField()),
                ('type_incident', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_order', models.CharField(max_length=255)),
                ('date_order', models.DateField()),
                ('period_execution', models.CharField(max_length=30)),
                ('price_order', models.IntegerField(default=0)),
                ('order_completion_status', models.CharField(max_length=30)),
                ('point_departure', models.CharField(max_length=255)),
                ('point_destination', models.CharField(max_length=255)),
                ('distance', models.IntegerField(default=0)),
                ('additional_information', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicle', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=30)),
                ('technical_condition', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('load_capacity', models.CharField(max_length=30)),
                ('insurance_information', models.CharField(max_length=255)),
            ],
        ),
    ]
