# Generated by Django 5.0 on 2023-12-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Грузы', 'verbose_name_plural': 'Грузы'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водители', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='incidents',
            options={'verbose_name': 'Происшествия', 'verbose_name_plural': 'Происшествия'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='transportation_categories',
            options={'verbose_name': 'Категории перевозок', 'verbose_name_plural': 'Категории перевозок'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_value',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_volume',
            field=models.CharField(max_length=30, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='dimensions',
            field=models.CharField(max_length=30, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.CharField(max_length=30, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='adress',
            field=models.CharField(max_length=30, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='inn',
            field=models.IntegerField(default=0, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name_client',
            field=models.CharField(max_length=30, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='number_telephone',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_telephone',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='pasport',
            field=models.CharField(max_length=30, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='work_experience',
            field=models.CharField(max_length=30, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='date_incident',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='name_incident',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_incident',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='type_incident',
            field=models.CharField(max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Доп информация'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_order',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='distance',
            field=models.IntegerField(default=0, verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name_order',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_completion_status',
            field=models.CharField(max_length=30, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='period_execution',
            field=models.CharField(max_length=30, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='point_departure',
            field=models.CharField(max_length=255, verbose_name='Точка отправки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='point_destination',
            field=models.CharField(max_length=255, verbose_name='Точка доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_order',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='transportation_categories',
            name='category_type',
            field=models.CharField(max_length=30, verbose_name='Тип категории'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_information',
            field=models.CharField(max_length=255, verbose_name='Инфо о страховке'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='load_capacity',
            field=models.CharField(max_length=30, verbose_name='Грузоподьемность'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=30, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='technical_condition',
            field=models.CharField(max_length=30, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(max_length=30, verbose_name='Тип'),
        ),
    ]
