# Generated by Django 5.0 on 2023-12-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_menu_alter_cargo_options_alter_clients_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
