# Generated by Django 4.2.7 on 2023-12-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_cards_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards_orders',
            name='image_card',
            field=models.ImageField(upload_to='transporations/images/', verbose_name='Изображение'),
        ),
    ]
