# Generated by Django 4.2.7 on 2024-01-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_type_transporation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transportation_categories',
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Груз', 'verbose_name_plural': 'Грузы'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='incidents',
            options={'verbose_name': 'Происшествие', 'verbose_name_plural': 'Происшествия'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техники'},
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='cargo_value',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='cargo_volume',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='distance',
        ),
        migrations.AddField(
            model_name='cargo',
            name='name_cargo',
            field=models.CharField(default=1, max_length=30, verbose_name='Название груза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='type_transportation',
            field=models.CharField(default=1, max_length=30, verbose_name='Тип перевозки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_order',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name_order',
            field=models.CharField(default='Заказ', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_completion_status',
            field=models.CharField(default='В обработке', max_length=30, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='period_execution',
            field=models.CharField(default='1 Неделя', max_length=30, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='point_departure',
            field=models.CharField(default='Москва', max_length=255, verbose_name='Точка отправки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='point_destination',
            field=models.CharField(default='Москва', max_length=255, verbose_name='Точка доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_order',
            field=models.CharField(default='0р.', max_length=10, verbose_name='Цена'),
        ),
    ]
