# Generated by Django 4.2.7 on 2024-01-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0008_delete_transportation_categories_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='name_cargo',
            field=models.CharField(max_length=30, verbose_name='Название груза...'),
        ),
    ]
