# Generated by Django 4.2.7 on 2024-01-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0009_alter_cargo_name_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cargo', models.CharField(max_length=30, verbose_name='Название груза...')),
                ('weight', models.CharField(max_length=30, verbose_name='Вес')),
                ('type', models.CharField(max_length=30, verbose_name='Тип')),
                ('dimensions', models.CharField(max_length=30, verbose_name='Габариты')),
                ('type_transportation', models.CharField(max_length=30, verbose_name='Тип перевозки')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
    ]
