# Generated by Django 4.2.7 on 2024-01-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='status',
            field=models.CharField(blank=True, max_length=30, verbose_name='Статус груза'),
        ),
    ]
