# Generated by Django 4.2.7 on 2024-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_cargos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='status',
            field=models.CharField(blank=True, default='Не выполнен', max_length=30, verbose_name='Статус груза'),
        ),
    ]
