# Generated by Django 4.2.7 on 2024-01-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0013_cargos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos',
            name='user',
        ),
    ]
